name: off_road_inclinometer
description: Inclinometer for off-road driving.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rive: ^0.8.1
  equatable: ^2.0.3
  intl: ^0.17.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  fluro: ^2.0.3
  rxdart: ^0.27.3
  flutter_sensors: ^1.0.1
  native_device_orientation: ^1.0.0
  shared_preferences: ^2.0.0-nullsafety
  url_launcher: ^6.0.20
  shimmer: ^2.0.0
  package_info_plus: ^1.4.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/gauge.riv
    - assets/icon/icon.png
    - assets/themes.json

flutter_intl:
  enabled: true
  arb_dir: lib/application/l10n
  output_dir: lib/application/l10n/generated